library(httr)
response1 <- GET(url = "https://bison.usgs.gov/")
response1.bin <- content(response1, "raw")
writeBin(response1.bin,"response1.html")
response2 <- GET(url = "https://bison.usgs.gov/doc/api.jsp")
response2.bin <- content(response2, "raw")
writeBin(response2.bin, "response2.html")
bison_base <- GET(url = "https://bison.usgs.gov/api/search.json")
meso_url <- GET(url = "https://mesonet.agron.iastate.edu/cgi-bin/request/asos.py/")
meso1 <- GET(url = meso_url)
class(meso1)