---
title: "Government Department Payroll"
author: 
  - name: Srihith Garlapati
date: "`r Sys.Date()`"
description: |
  These graphs below show the total amount of earnings each government department(GD) in each state earn annually.
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(janitor)
# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

```{r, layout = "l-page", include = FALSE}
x <- read_csv(file = "2020_state.xls - 2020_state.csv", skip = 14)


```
## USA Graph
```{r, raw_data, x}
raw_data <- x %>%  
  clean_names() %>% 
  slice(2:38) %>%
  select(government_function, whole_dollars) %>%
  filter(whole_dollars > 100000000) %>%
  ggplot(mapping = aes(x = whole_dollars, y = fct_reorder(government_function, whole_dollars), fill = government_function)) + 
  geom_col(alpha = 0.5) + 
  labs(title = "Total Earnings Per GD in the USA", 
       subtitle = "The Education department which includes primary \nand secondary education gets the most amount \nof money annually",
       x = "Money earned",
       y = "Government Job Department",
       fill = NULL) + 
  scale_fill_discrete(guide=FALSE) +
  theme_classic() +
  scale_x_continuous(labels = scales::number_format())

raw_data
```

```{r, table_1, include = FALSE }
regions <- x %>%  
  clean_names() %>% 
  slice(39:1938)  %>%
  select(state, government_function, whole_dollars) %>%
  mutate(region = case_when(state %in% c("IN", "IL", "IA", "MN", "MI", "WI", "OH")~"Midwest",
                            state %in% c("VA", "WV", "KY", "TN", "NC", "SC", "GA", "AL", "MS", "LA", "AR", "FL")~"South",
                            state %in% c("PA", "NY", "VT", "ME", "NH", "MA", "RI", "NJ", "CT", "DE", "MD")~"Northeast",
                            state %in% c("NT", "ND", "SD", "NE", "KS", "CO", "WY")~"Central",
                            state %in% c("WA", "OR", "ID", "NV", "UT", "CA", "AK", "HI")~"West",
                            state %in% c("AZ", "NH", "TX", "OK")~"Southwest")) %>%
  group_by(region)
regions

```
## Southwest Region Graph
```{r}
regions %>% 
  filter(region == "Southwest") %>%
  group_by(government_function) %>%
  summarize(region = region, total = sum(whole_dollars)) %>%
  unique() %>%
  filter(total > 10000000, !government_function == "Total - All Government Employment Functions") %>%
  ggplot(mapping = aes(x = total, y = fct_reorder(government_function, total))) + 
  geom_col(alpha = 0.5) + 
  labs(title = "Total Earnings per GD in the Southwest Region", 
       subtitle = "The Education department which includes primary \nand secondary education gets the most amount \nof money annually",
       x = "Money earned",
       y = "Government Job Department") + 
  scale_fill_discrete(guide=FALSE) +
  theme_classic() +
  scale_x_continuous(labels = scales::number_format())
```
## Central Region Graph
```{r}
regions %>% 
  filter(region == "Central") %>%
  group_by(government_function) %>%
  summarize(region = region, total = sum(whole_dollars)) %>%
  unique() %>%
  filter(total > 10000000, !government_function == "Total - All Government Employment Functions") %>%
  ggplot(mapping = aes(x = total, y = fct_reorder(government_function, total))) + 
  geom_col(alpha = 0.5) + 
  labs(title = "Total Earnings per GD in the Central Region", 
       subtitle = "The Education department which includes primary \nand secondary education gets the most amount \nof money annually",
       x = "Money earned",
       y = "Government Job Department") + 
  scale_fill_discrete(guide=FALSE) +
  theme_classic() +
  scale_x_continuous(labels = scales::number_format())
```
## Midwest Region Graph
```{r, table_2}
regions %>% 
  filter(region == "Midwest") %>%
  group_by(government_function) %>%
  summarize(region = region, total = sum(whole_dollars)) %>%
  unique() %>%
  filter(total > 10000000, !government_function == "Total - All Government Employment Functions") %>%
  ggplot(mapping = aes(x = total, y = fct_reorder(government_function, total))) + 
  geom_col(alpha = 0.5) + 
  labs(title = "Total Earnings per GD in the Midwest Region", 
       subtitle = "The Education department which includes primary \nand secondary education gets the most amount \nof money annually",
       x = "Money earned",
       y = "Government Job Department") + 
  scale_fill_discrete(guide=FALSE) +
  theme_classic() +
  scale_x_continuous(labels = scales::number_format())
  

```
## Northeast Region Graph
```{r}
regions %>% 
  filter(region == "Northeast") %>%
  group_by(government_function) %>%
  summarize(region = region, total = sum(whole_dollars)) %>%
  unique() %>%
  filter(total > 10000000, !government_function == "Total - All Government Employment Functions") %>%
  ggplot(mapping = aes(x = total, y = fct_reorder(government_function, total))) + 
  geom_col(alpha = 0.5) + 
  labs(title = "Total Earnings Per GD in the Northeast Region", 
       subtitle = "The Education department which includes primary \nand secondary education gets the most amount \nof money annually",
       x = "Money earned",
       y = "Government Job Department") + 
  scale_fill_discrete(guide=FALSE) +
  theme_classic() +
  scale_x_continuous(labels = scales::number_format())
```
## West Region Graph
```{r}
regions %>% 
  filter(region == "West") %>%
  group_by(government_function) %>%
  summarize(region = region, total = sum(whole_dollars)) %>%
  unique() %>%
  filter(total > 10000000, !government_function == "Total - All Government Employment Functions") %>%
  ggplot(mapping = aes(x = total, y = fct_reorder(government_function, total))) + 
  geom_col(alpha = 0.5) + 
  labs(title = "Total Earnings Per GD in the West Region", 
       subtitle = "The Education department which includes primary \nand secondary education gets the most amount \nof money annually",
       x = "Money earned",
       y = "Government Job Department") + 
  scale_fill_discrete(guide=FALSE) +
  theme_classic() +
  scale_x_continuous(labels = scales::number_format())
```
## South Region Graph
```{r}
regions %>% 
  filter(region == "South") %>%
  group_by(government_function) %>%
  summarize(region = region, total = sum(whole_dollars)) %>%
  unique() %>%
  filter(total > 10000000, !government_function == "Total - All Government Employment Functions") %>%
  ggplot(mapping = aes(x = total, y = fct_reorder(government_function, total))) + 
  geom_col(alpha = 0.5) + 
  labs(title = "Total Earnings Per GD in the South Region", 
       subtitle = "The Education department which includes primary \nand secondary education gets the most amount \nof money annually",
       x = "Money earned",
       y = "Government Job Department") + 
  scale_fill_discrete(guide=FALSE) +
  theme_classic() +
  scale_x_continuous(labels = scales::number_format())
```